# This file was generated by the {rix} R package v0.15.5 on 2025-03-20
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
  # Calculate the sha256 using:
  # nix-prefetch-url --unpack "https://github.com/rstats-on-nix/nixpkgs/archive/2025-03-03.tar.gz"
  nixpkgs_src = fetchTarball {
    url = "https://github.com/rstats-on-nix/nixpkgs/archive/2025-03-03.tar.gz";
    # Replace the placeholder below with the actual hash you calculated!
    sha256 = "1c7mb76w0qxv2gihblk42hlj08dqvmfyd4350j8in6v5kxp79p71";
  };

  pkgs = import nixpkgs_src { config.allowUnfree = true; };

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      devtools
      dplyr
      pacman
      pak
      rix;
  };

  system_packages = builtins.attrValues {
    inherit (pkgs)
      gettext
      git
      glibcLocales
      nix
      positron-bin
      R
      radianWrapper
      toybox;
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ rpkgs  system_packages   ];

}
